val version : string
val build_arch : string
val build_mode : string
val build_date : string

external init : unit -> unit = "ocamlyices_init"
external reset : unit -> unit = "ocamlyices_reset"
external exit : unit -> unit = "ocamlyices_exit"

type typ
external int_type : unit -> typ = "ocamlyices_int_type"
external bool_type : unit -> typ = "ocamlyices_bool_type"
external real_type : unit -> typ = "ocamlyices_real_type"
external bv_type : int -> typ = "ocamlyices_bv_type"
external new_scalar_type : int -> typ = "ocamlyices_new_scalar_type"
external new_uninterpreted_type : int -> typ = "ocamlyices_new_uninterpreted_type"
external tuple_type : typ array -> typ = "ocamlyices_tuple_type"
external function_type : typ array -> typ -> typ = "ocamlyices_function_type"

type term
external true_ : unit -> term = "ocamlyices_true"
external false_ : unit -> term = "ocamlyices_true"
external constant : typ -> int -> term = "ocamlyices_constant"
external new_uninterpreted_term : typ -> term = "ocamlyices_new_uninterpreted_term"
external new_variable : typ -> term = "ocamlyices_new_variable"
external application : term -> term array -> term = "ocamlyices_application"

external eq : term -> term -> term = "ocamlyices_eq"
external neq : term -> term -> term = "ocamlyices_neq"
external not : term -> term = "ocamlyices_not"
external andn : term array -> term = "ocamlyices_and"
external orn : term array -> term = "ocamlyices_or"
external xorn : term array -> term = "ocamlyices_xor"
external and2 : term -> term -> term = "ocamlyices_and2"
external or2 : term -> term -> term = "ocamlyices_or2"
external xor2 : term -> term -> term = "ocamlyices_xor2"
external and3 : term -> term -> term -> term = "ocamlyices_and3"
external or3 : term -> term -> term -> term = "ocamlyices_or3"
external xor3 : term -> term -> term -> term = "ocamlyices_xor3"
external iff : term -> term -> term = "ocamlyices_iff"
external implies : term -> term -> term = "ocamlyices_implies"
external tuple : term array -> term = "ocamlyices_tuple"
external select : int -> term -> term = "ocamlyices_select"
external tuple_update : term -> int -> term -> term = "ocamlyices_tuple_update"
external update : term -> term array -> term -> term = "ocamlyices_update"
external distinct : term array -> term = "ocamlyices_distinct"
external forall : term array -> term -> term = "ocamlyices_forall"
external exists : term array -> term -> term = "ocamlyices_exists"
external zero : unit -> term = "ocamlyices_zero"
external int_ : int -> term = "ocamlyices_int"
external int32_ : int32 -> term = "ocamlyices_int32"
external int64_ : int64 -> term = "ocamlyices_int64"
external rational : int -> int -> term = "ocamlyices_rational"
external rational32 : int32 -> int32 -> term = "ocamlyices_rational32"
external rational64 : int64 -> int64 -> term = "ocamlyices_rational64"
external parse_rational : string -> term = "ocamlyices_parse_rational"
external parse_float : string -> term = "ocamlyices_parse_float"
external add : term -> term -> term = "ocamlyices_add"
external sub : term -> term -> term = "ocamlyices_sub"
external neg : term -> term = "ocamlyices_neg"
external mul : term -> term -> term = "ocamlyices_mul"
external square : term -> term = "ocamlyices_square"
